### PR TITLE
updated macro directory

### PR DESCRIPTION
**Pull request by nathandunn**

### CODE REVIEW

**Comment by erasche** [comment]
https://github.com/erasche/docker-galaxy-annotation/blob/24ba62981c4b35ae403f9e36b30cf5357fb69ffa/postinst.sh

Does the new image from quay.io correct this, or is this fix still needed?

**Comment by nathandunn** [comment]
@erasche   Let me take a look

**Comment by nathandunn** [comment]
@erasche  It doesn't seem to be fixed:

https://github.com/TAMU-CPT/galaxy-webapollo/blob/master/macros.xml#L10

is wrong.  The change I have is correct.   I switched to use the image:

    quay.io/erasche/docker-galaxy-annotation

and I get the same result.

**Comment by erasche** [comment]
Looks like my postinst had a trailing slash, but this should be doubly fixed now. Cheers @nathandunn

**Comment by nathandunn** [comment]
👍

**Pull request merged**
